<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php 
    $X = 3;
    $Y = 5;
    echo "<h3>Trường hợp 1: x =3 và y = 5</h3>";
    echo "Cộng: " . ($X + $Y) . "<br>";
    echo "Trừ: " . ($X - $Y) . "<br>";
    echo "Nhân: " . ($X * $Y) . "<br>";
    echo "Chia: " . ($X / $Y) . "<br>";
    echo "Mod: " . ($X % $Y) . "<br>";
    ?>

    
</body>
</html>